### ISSUE TITLE
Svtplay's Plugin is currently broken

### ISSUE THREAD

**Issue by kvn1351** [streamlink/streamlink#3133]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

The svtplay plugin seems to be broken. Every url I have tested yield the same error. Other Swedish geo-restricted sites work fine.

I'm on the latest streamlink 1.5.0 on Windows 10.

### Reproduction steps / Explicit stream URLs to test

1. Go to Svtplay.se with a Swedish Ip, Vpn or Proxy.
2. Pick some show and it's URL
3. Try to stream it with streamlink

### Log output

```
streamlink https://www.svtplay.se/video/27096341/sportnytt/sportnytt-28-aug-22-00-3
[cli][info] Found matching plugin svtplay for URL https://www.svtplay.se/video/27096341/sportnytt/sportnytt-28-aug-22-00-3
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ('<!DOCTYPE html>\n\n<head>\n    <me ...)
```

### Additional comments, screenshots, etc.

Thanks a lot for your support!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
@kvn1351, I have updated the regex.  You can get the whole plugin for testing from:

https://github.com/mkbloke/streamlink/blob/svtplay/src/streamlink/plugins/svtplay.py

Just select raw, then file/save as in your browser to download it.

Alternatively, you can just edit your existing plugin to update the regex on line 21 to:

```_id_re = re.compile(r'DATA_LAKE = {"content":{"id":"(?P<id>[^"]+)"')```

If the plugin works for you with that change, I'll create a PR for it.  Cheers.

**Comment by mkbloke** [comment]
@kvn1351, just to add, if you can test the change against a number of different URLs, that would be very helpful, thanks.

**Comment by mkbloke** [comment]
I've just pushed another minor improvement on this plugin, so rather than changing the single line as I mentioned previously, it would be better to download the whole updated plugin from:

https://github.com/mkbloke/streamlink/blob/svtplay/src/streamlink/plugins/svtplay.py

The minor improvement allows the plugin to also pick up the correct video page when given a landing page like:

https://www.svtplay.se/dokument-inifran-att-radda-ett-barn

Cheers.

**Comment by DanOscarsson** [comment]
It still does not work for the direct channel pages like:
https://www.svtplay.se/kanaler/svt1

Worked fine there before so the change they have done also makes this page fail.

**Comment by mkbloke** [comment]
Thanks for the report, @DanOscarsson.

I think I'm going to somewhat start from the beginning with this plugin, gathering the possible URLs under svtplay.se and oppetarkiv.se to start with, with a view to removing the support for the 'old' format if I cannot find any URLs where keeping it would be necessary.

I'll likely also drop support for svtflow.se unless I can find any reason for keeping it, as the one URL to content on svtflow.se that I've found with a Google search just results in a redirect to the home page on svtplay.se.

**Comment by PCarlsson** [comment]
Let me know if I can assist in any way.

**Comment by mkbloke** [comment]
Hi all.  I've been testing this updated plugin on various URLs for both svtplay.se and oppetarkiv.se sites.  It seems to be working, so if anybody would like to test and report back, that would be most welcome.

I've pushed the most recent changes to: https://github.com/mkbloke/streamlink/blob/svtplay/src/streamlink/plugins/svtplay.py

This plugin now supports the ```--title``` option, where data is available, so you can for example use:

```--title '{title} - {author} - {category}'```

You can also multiplex in subtitles for VODs where they are available using the ```--svtplay-mux-subtitles``` option.

Cheers.

**Comment by PCarlsson** [comment]
Hello!

I can confirm that it works for the following URLs:
- https://www.svtplay.se/kanaler/svt1?start=auto
- https://www.svtplay.se/kanaler/svt2?start=auto
- https://www.svtplay.se/kanaler/kunskapskanalen?start=auto
- https://www.svtplay.se/kanaler/svtbarn?start=auto
- https://www.svtplay.se/kanaler/svt24?start=auto

I have not tested the options though.

Great work!

**Comment by mkbloke** [comment]
Thanks for the feedback.

**Comment by DanOscarsson** [comment]
I tested also the www.svtplay.se/kanaler/svt1 and www.svtplay.se/kanaler/svt2 links as I use those. I have used them in a script calling:
streamlink --stream-url www.svtplay.se/kanaler/svt1 best 
and then using the returned URL with mpv to show it.
With this fix that no longer works as the above command returns like:
https://site/xx/yy/manifest.mpd?defaultSubLang=1
which mpv does not understand
On the other hand, if I call streamlink with -o to save to a file or with -p mpv
so streamlink itself takes down the data, it works fine.

I can easily change my scripts so they work, but should not --stream-url return a stream url?

**Comment by mkbloke** [comment]
@DanOscarsson, it is a stream URL that is returned, but it's a DASH stream.  It seems both VLC and MPV can have issues with DASH manifests, which streamlink can happily parse.

I could look at putting HLS support back in, although previously I had issues with the subtitle muxing under HLS.

**Comment by DanOscarsson** [comment]
As if works fine by having streamlink handle the data and sending it to mpv that is not necessary for my needs. I will just change my scripts a little.
As you talked about HLS I tested:
streamlink --stream-types hls --stream-url www.svtplay.se/kanaler/svt1 best
which returns
error: No playable streams found on this URL: www.svtplay.se/kanaler/svt1
which I assume is because HLS support is missing or not available.
But no need to add HLS support for me as I can make it work as it is now.
If there always will be DASH streams or if there can be HLS streams with higher resolution I have no idea, but could be cases where alternative formats could be wanted.

**Comment by Tigge** [comment]
Seems broken for https://www.svtplay.se/video/21095160/bamse-och-tjuvstaden/bamse-och-tjuvstaden-sasong-1-avsnitt-1?start=auto as well

**Comment by mkbloke** [comment]
It should be fixed by: https://github.com/streamlink/streamlink/blob/0c9a878d96a0b607919e221f275fb64e8be1627c/src/streamlink/plugins/svtplay.py

Hopefully it'll be merged into master soon.  Cheers.
